Repository AY2324S2-CS2103T-F13-4/tp, pull requests merged in 2024-04, with the labels that each got.

#82 Update UG to not use admonitions
  docs/UserGuide.md
Labels: documentation

#87 Update UG for edit, star and bolt command
  docs/UserGuide.md
  docs/images/bolt.png
  docs/images/star.png
Labels: documentation

#89 Actually fix the bugs for bullet points
  docs/UserGuide.md
Labels: bug, documentation

#91 Seriously fix this bulleting issue
  docs/UserGuide.md
Labels: bug, documentation

#79 Sort by Bolt and change default sort
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Bolt.java
Labels: bug

#95 Update docs index.md
  docs/index.md
Labels: documentation

#146 Enfoce limits for bolt and edit commands
  src/main/java/seedu/address/logic/commands/BoltCommand.java
  src/main/java/seedu/address/logic/parser/BoltCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Bolt.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/parser/BoltCommandParserTest.java
Labels: bug

#149 Fix ug issues regarding address and addressbook references
  docs/UserGuide.md
Labels: documentation

#151 Fix major error message
  src/main/java/seedu/address/model/student/Major.java
Labels: documentation

#159 Update dg style
  docs/DeveloperGuide.md
Labels: documentation

#158 Add toc sidebar
  docs/UserGuide.md
Labels: documentation

#171 Format example for star and bolt command to make it beautiful
  docs/UserGuide.md
Labels: documentation

#172 Update find command format in UG
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/findNameAlexDavidResult.png
Labels: documentation, ped-fix-ug

#168 Specify that bolt is for absenteeism only
  docs/UserGuide.md
Labels: documentation

#177 Format and standardize UG
  docs/UserGuide.md
  docs/images/add.png
  docs/images/sort.png
  docs/images/sortBoltDesc.png
Labels: documentation

#193 Add acknowledgements to DG
  docs/DeveloperGuide.md
Labels: documentation
