Repository AY2324S2-CS2103T-F13-4/tp, pull requests merged in 2024-03, with the labels that each got.

#22 Fix style in DG
  docs/DeveloperGuide.md
Labels: documentation

#26 Add star command
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/StarCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StarCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Star.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: key feature

#33 Update user guide to include Star command
  docs/UserGuide.md
Labels: documentation

#35 Add find stars less than
  src/main/java/seedu/address/logic/commands/FindStarsLessThanCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindStarsLessThanCommandParser.java
  src/main/java/seedu/address/model/person/StarsLessThanPredicate.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/FindStarsLessThanCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindStarsLessThanCommandParserTest.java
  src/test/java/seedu/address/model/person/StarsLessThanPredicateTest.java
Labels: key feature

#43 Update UML Diagram for Model Component
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation

#44 Add sequence diagram of findStarsLT
  docs/DeveloperGuide.md
  docs/diagrams/FindStarsLessThanSequenceDiagram.puml
  docs/images/FindStarsLessThanSequenceDiagram.png
Labels: documentation

#56 Refine sequence diagram and update DG
  docs/DeveloperGuide.md
  docs/diagrams/BoltCommandSequenceDiagram.puml
  docs/diagrams/StarCommandSequenceDiagram.puml
  docs/images/BoltCommandSequenceDiagram.png
  docs/images/StarCommandSequenceDiagram.png
Labels: documentation

#61 Implement general find command
  docs/diagrams/FindStarsLessThanSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindStarsLessThanCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindStarsLessThanCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/student/StarsLessThanPredicate.java
  src/main/java/seedu/address/model/student/predicates/BoltWithinBoundsPredicate.java
  src/main/java/seedu/address/model/student/predicates/MajorContainsSubStringPredicate.java
  src/main/java/seedu/address/model/student/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/student/predicates/StarWithinBoundsPredicate.java
  src/main/java/seedu/address/model/student/predicates/TagContainsSubStringPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindStarsLessThanCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindStarsLessThanCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/student/predicates/BoltWithinBoundsPredicateTest.java
  src/test/java/seedu/address/model/student/predicates/MajorContainsSubStringPredicateTest.java
  src/test/java/seedu/address/model/student/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/predicates/StarWithinBoundsPredicateTest.java
Labels: enhancement

#69 Fix bugs in DG
  docs/DeveloperGuide.md
Labels: documentation

#71 Fix sizing of SortCommandSequenceDiagram
  docs/images/SortCommandSequenceDiagram.png
Labels: bug
